version: 2
updates:
  # Automatic updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    # Cooldown period: wait before creating PRs for new releases
    cooldown:
      default-days: 7
    insecure-external-code-execution: deny
    rebase-strategy: "auto"
    groups:
      # Group all development dependencies into a single PR
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      # Production dependencies are updated individually
      production-dependencies:
        dependency-type: "production"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "dyoshikawa"
      - "cm-dyoshikawa"
    # Enable versioning strategy for better auto-merge compatibility
    versioning-strategy: "increase"
    allow:
      # Allow all security updates
      - dependency-type: "all"
    ignore:
      # Add specific packages to ignore here if needed
      # - dependency-name: "example-package"
      #   versions: ["2.x", "3.x"]

  # Automatic updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    # Cooldown period for GitHub Actions updates
    cooldown:
      default-days: 7
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "automated"
    reviewers:
      - "dyoshikawa"